//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTrackerApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;

    public partial class expense
    {
        
        public int ID { get; set; }
        [Required]
        [Display(Name ="Title")]
        public string Title { get; set; }
        [Required]
        [Display(Name ="Description")]
        public string Description { get; set; }
        [Required]
        [Display(Name ="Ampount")]
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Category_ID { get; set; }
        [Required]
        [Display(Name ="DD/MM/YYYY")]
        public Nullable<System.DateTime> Date_Time { get; set; }
    
        public virtual category category { get; set; }
    }
}
